TITLE           = 'title'
ORGANIZATION    = 'organization'
LOCATION        = 'location'
DESCRIPTION     = 'description'
TECH_STACK      = 'tech_stack'
INTERNSHIP_DURAION = 'internship_duration'
WORK_DURAION = 'work_duration'