HEADER              = 'header'
EDUCATION           = 'education'
INTERNSHIPS         = 'internships'
WORK_EXPERIENCES    = 'work_experiences'
PROJECTS            = 'projects'
SKILLSET            = 'skillset'
ACHIEVEMENTS         = 'achievements'